server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://192.168.12.99:3306/dev?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.12.99
    # Redis服务器连接端口
    port: 6379
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池中的最小空闲连接
      max-idle: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
logging:
  level:
    com.crystal.feature.mapper: debug
